
import React from 'react';

export const TRANSLATIONS = {
  en: {
    appName: "Give Me the Line",
    newScene: "New Scene",
    myScenes: "My Scenes",
    noScenes: "No scenes yet. Create your first one!",
    title: "Title",
    script: "Script Text",
    pasteScript: "Paste your theater or movie script here...",
    parse: "Parse Script",
    parsing: "Analyzing...",
    me: "MINE",
    partner: "VOICE",
    rehearse: "Start Rehearsal",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    back: "Back",
    next: "Next",
    finish: "Finish",
    record: "Record",
    stop: "Stop",
    play: "Play",
    help: "Help",
    settings: "Settings",
    language: "Language",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    system: "System",
    support: "Support the Project",
    author: "Author: Vladimir Kisarov",
    guideTitle: "User Guide",
    guideIntro: "Give Me the Line is your digital prompter. Here's how to use it:",
    guideSteps: [
      "Create a scene and paste your script.",
      "The app automatically parses characters and lines.",
      "Assign roles: 'MINE' for your lines, 'VOICE' for lines you want to hear played back.",
      "Record audio for each 'VOICE' line so you can rehearse with them.",
      "Enter Rehearsal mode to practice with the prompter."
    ]
  },
  ru: {
    appName: "Подай Реплику",
    newScene: "Новая сцена",
    myScenes: "Мои сцены",
    noScenes: "Сцен пока нет. Создайте свою первую!",
    title: "Название",
    script: "Текст сценария",
    pasteScript: "Вставьте текст пьесы или киносценария...",
    parse: "Разобрать текст",
    parsing: "Разбираем...",
    me: "МОЯ",
    partner: "ГОЛОС",
    rehearse: "Репетировать",
    edit: "Редактировать",
    delete: "Удалить",
    save: "Сохранить",
    back: "Назад",
    next: "Далее",
    finish: "Завершить",
    record: "Запись",
    stop: "Стоп",
    play: "Слушать",
    help: "Помощь",
    settings: "Настройки",
    language: "Язык",
    theme: "Тема",
    light: "Светлая",
    dark: "Тёмная",
    system: "Системная",
    support: "Поддержать проект",
    author: "Автор: Владимир Кисаров",
    guideTitle: "Инструкция",
    guideIntro: "«Подай Реплику» — ваш цифровой суфлёр. Вот как это работает:",
    guideSteps: [
      "Создайте сцену и вставьте текст сценария.",
      "Приложение автоматически определит персонажей и реплики.",
      "Распределите роли: 'МОЯ' для ваших реплик, 'ГОЛОС' для реплик, которые будут звучать.",
      "Запишите аудио для каждой реплики с пометкой 'ГОЛОС'.",
      "Запустите режим репетиции для работы с суфлёром."
    ]
  },
  es: {
    appName: "Dame la Línea",
    newScene: "Nueva Escena",
    myScenes: "Mis Escenas",
    noScenes: "¡Crea la primera!",
    title: "Título",
    script: "Texto del Guion",
    pasteScript: "Pega tu guion de teatro o cine aquí...",
    parse: "Analizar Guion",
    parsing: "Analizando...",
    me: "MÍA",
    partner: "VOZ",
    rehearse: "Ensayar",
    edit: "Editar",
    delete: "Eliminar",
    save: "Guardar",
    back: "Atrás",
    next: "Siguiente",
    finish: "Finalizar",
    record: "Grabar",
    stop: "Parar",
    play: "Reproducir",
    help: "Ayuda",
    settings: "Ajustes",
    language: "Idioma",
    theme: "Tema",
    light: "Claro",
    dark: "Oscuro",
    system: "Sistema",
    support: "Apoyar el proyecto",
    author: "Autor: Vladimir Kisarov",
    guideTitle: "Guía de Usuario",
    guideIntro: "Dame la Línea es tu apuntador digital. Así se usa:",
    guideSteps: [
      "Crea una escena y pega tu guion.",
      "La app analiza automáticamente personajes y líneas.",
      "Asigna roles: 'MÍA' para tus líneas, 'VOZ' para las que quieres oír grabadas.",
      "Graba audio para cada línea de 'VOZ'.",
      "Entra en modo Ensayo para practicar con el apuntador."
    ]
  }
};

export const SUPPORT_LINK = "https://pay.cloudtips.ru/p/b93104a4";
export const AUTHOR_LINK = "https://vladimirkisarov.ru/";
